steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/snore-api/snoreff', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/snore-api/snoreff']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'snoreff'
    - '--image'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/snore-api/snoreff'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'

substitutions:
  _REGION: 'us-central1'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/snore-api/snoreff'
