name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Authenticate to Google Cloud
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account.json
        gcloud auth activate-service-account --key-file=/tmp/service-account.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Enable required APIs (optional)
      run: |
        gcloud services enable artifactregistry.googleapis.com || echo "Artifact Registry API already enabled or permission denied"
        gcloud services enable run.googleapis.com || echo "Cloud Run API already enabled or permission denied"
        gcloud services enable cloudbuild.googleapis.com || echo "Cloud Build API already enabled or permission denied"
        
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
        
    - name: Create Artifact Registry repository (if not exists)
      run: |
        gcloud artifacts repositories create snore-api \
          --repository-format=docker \
          --location=${{ secrets.GCP_REGION }} \
          --description="Docker repository for snore detection API" || true
        
    - name: Build and push image
      run: |
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/snore-api/snoreff .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/snore-api/snoreff
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy snoreff \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/snore-api/snoreff \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8080
